# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplyWidget.ui'
#
# Created: Fri Apr  8 17:47:19 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(337, 173)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_3 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.Frame_2 = QtGui.QFrame(self.frame_3)
        self.Frame_2.setProperty("PeripheralCollectionInner", _fromUtf8(""))
        self.Frame_2.setObjectName(_fromUtf8("Frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Frame_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.PCS_LABEL = QtGui.QLabel(self.Frame_2)
        self.PCS_LABEL.setObjectName(_fromUtf8("PCS_LABEL"))
        self.gridLayout_2.addWidget(self.PCS_LABEL, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.PV3_LABEL = QtGui.QLabel(self.Frame_2)
        self.PV3_LABEL.setObjectName(_fromUtf8("PV3_LABEL"))
        self.gridLayout_2.addWidget(self.PV3_LABEL, 2, 1, 1, 1)
        self.PV2_LABEL = QtGui.QLabel(self.Frame_2)
        self.PV2_LABEL.setObjectName(_fromUtf8("PV2_LABEL"))
        self.gridLayout_2.addWidget(self.PV2_LABEL, 1, 1, 1, 1)
        self.PV1_LABEL = QtGui.QLabel(self.Frame_2)
        self.PV1_LABEL.setObjectName(_fromUtf8("PV1_LABEL"))
        self.gridLayout_2.addWidget(self.PV1_LABEL, 0, 1, 1, 1)
        self.PV1BOX = QtGui.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PV1BOX.sizePolicy().hasHeightForWidth())
        self.PV1BOX.setSizePolicy(sizePolicy)
        self.PV1BOX.setDecimals(3)
        self.PV1BOX.setMinimum(-5.0)
        self.PV1BOX.setMaximum(5.0)
        self.PV1BOX.setSingleStep(0.1)
        self.PV1BOX.setObjectName(_fromUtf8("PV1BOX"))
        self.gridLayout_2.addWidget(self.PV1BOX, 0, 2, 1, 1)
        self.PV2BOX = QtGui.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PV2BOX.sizePolicy().hasHeightForWidth())
        self.PV2BOX.setSizePolicy(sizePolicy)
        self.PV2BOX.setDecimals(3)
        self.PV2BOX.setMinimum(-3.3)
        self.PV2BOX.setMaximum(3.3)
        self.PV2BOX.setSingleStep(0.1)
        self.PV2BOX.setObjectName(_fromUtf8("PV2BOX"))
        self.gridLayout_2.addWidget(self.PV2BOX, 1, 2, 1, 1)
        self.PV3BOX = QtGui.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PV3BOX.sizePolicy().hasHeightForWidth())
        self.PV3BOX.setSizePolicy(sizePolicy)
        self.PV3BOX.setDecimals(3)
        self.PV3BOX.setMaximum(3.3)
        self.PV3BOX.setSingleStep(0.1)
        self.PV3BOX.setObjectName(_fromUtf8("PV3BOX"))
        self.gridLayout_2.addWidget(self.PV3BOX, 2, 2, 1, 1)
        self.PCSBOX = QtGui.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PCSBOX.sizePolicy().hasHeightForWidth())
        self.PCSBOX.setSizePolicy(sizePolicy)
        self.PCSBOX.setDecimals(3)
        self.PCSBOX.setMaximum(3.3)
        self.PCSBOX.setSingleStep(0.1)
        self.PCSBOX.setObjectName(_fromUtf8("PCSBOX"))
        self.gridLayout_2.addWidget(self.PCSBOX, 3, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.Frame_2)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.PV1BOX, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.setPV1)
        QtCore.QObject.connect(self.PV2BOX, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.setPV2)
        QtCore.QObject.connect(self.PV3BOX, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.setPV3)
        QtCore.QObject.connect(self.PCSBOX, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.setPCS)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.frame_3.setProperty("class", _translate("Form", "PeripheralCollection", None))
        self.label_2.setText(_translate("Form", " IV Sources", None))
        self.Frame_2.setProperty("class", _translate("Form", "PeripheralCollectionInner", None))
        self.label_10.setText(_translate("Form", "PV3", None))
        self.label_12.setText(_translate("Form", "PV2 ", None))
        self.label_11.setText(_translate("Form", "PV1 ", None))
        self.PCS_LABEL.setText(_translate("Form", "0-3.3mA", None))
        self.label_9.setText(_translate("Form", "PCS", None))
        self.PV3_LABEL.setText(_translate("Form", "0 - 3.3V", None))
        self.PV2_LABEL.setText(_translate("Form", "-3.3 to 3.3V", None))
        self.PV1_LABEL.setText(_translate("Form", "-5 to 5V", None))

