# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digitalScope.ui'
#
# Created: Wed Feb 17 14:13:41 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(889, 577)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/pixmaps/cubeview48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888);\n"
"min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}\n"
"\n"
"QFrame.PeripheralCollection{\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border: 1px solid black;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #ebc, stop: 0.1 #689);\n"
"}\n"
"\n"
"QFrame.PeripheralCollection QLabel {\n"
"color: white;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QFrame.PeripheralCollectionInner {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #abe, stop: 0.7 #aba);\n"
"border: none;\n"
"border-top: 3px solid black;\n"
"}\n"
"\n"
"QFrame.PeripheralCollectionInner QLabel{\n"
"color: black;\n"
"}\n"
"\n"
"\n"
"#centralwidget{\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border: 1px solid black;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #6af, stop: 0.1 #689);\n"
"}\n"
"#centralwidget QLabel {\n"
"color: black;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
""))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.plot_area_frame = QtGui.QFrame(self.splitter)
        self.plot_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_area_frame.setObjectName(_fromUtf8("plot_area_frame"))
        self.plot_area = QtGui.QVBoxLayout(self.plot_area_frame)
        self.plot_area.setSpacing(2)
        self.plot_area.setMargin(2)
        self.plot_area.setObjectName(_fromUtf8("plot_area"))
        self.frame_12 = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setStyleSheet(_fromUtf8(""))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.frame_7 = QtGui.QFrame(self.frame_12)
        self.frame_7.setGeometry(QtCore.QRect(10, 370, 281, 131))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.edge2chan = QtGui.QComboBox(self.frame_7)
        self.edge2chan.setObjectName(_fromUtf8("edge2chan"))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2chan, 2, 1, 1, 1)
        self.edge1edge = QtGui.QComboBox(self.frame_7)
        self.edge1edge.setObjectName(_fromUtf8("edge1edge"))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1edge, 1, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.edge2edge = QtGui.QComboBox(self.frame_7)
        self.edge2edge.setObjectName(_fromUtf8("edge2edge"))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2edge, 2, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.edge1chan = QtGui.QComboBox(self.frame_7)
        self.edge1chan.setObjectName(_fromUtf8("edge1chan"))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1chan, 1, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 3)
        self.pushButton_6 = QtGui.QPushButton(self.frame_7)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_4.addWidget(self.pushButton_6, 3, 0, 1, 3)
        self.time_interval_label = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.time_interval_label.setFont(font)
        self.time_interval_label.setObjectName(_fromUtf8("time_interval_label"))
        self.gridLayout_4.addWidget(self.time_interval_label, 6, 0, 1, 3)
        self.label_13 = QtGui.QLabel(self.frame_12)
        self.label_13.setGeometry(QtCore.QRect(20, 80, 71, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.frame_5 = QtGui.QFrame(self.frame_12)
        self.frame_5.setGeometry(QtCore.QRect(10, 180, 281, 181))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout = QtGui.QFormLayout(self.frame_5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_54 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_54)
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.comboBox_2 = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.label_11 = QtGui.QLabel(self.frame_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.comboBox_3 = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_3)
        self.label_12 = QtGui.QLabel(self.frame_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_12)
        self.comboBox_4 = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_4)
        self.frame_10 = QtGui.QFrame(self.frame_5)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_29 = QtGui.QLabel(self.frame_10)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_2.addWidget(self.label_29)
        self.LA1_trig = QtGui.QComboBox(self.frame_10)
        self.LA1_trig.setObjectName(_fromUtf8("LA1_trig"))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.LA1_trig)
        self.LA1_trigmode = QtGui.QComboBox(self.frame_10)
        self.LA1_trigmode.setObjectName(_fromUtf8("LA1_trigmode"))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.LA1_trigmode)
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.frame_10)
        self.active_channel_box = QtGui.QComboBox(self.frame_12)
        self.active_channel_box.setGeometry(QtCore.QRect(110, 80, 61, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_channel_box.sizePolicy().hasHeightForWidth())
        self.active_channel_box.setSizePolicy(sizePolicy)
        self.active_channel_box.setObjectName(_fromUtf8("active_channel_box"))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.frame_8 = QtGui.QFrame(self.frame_12)
        self.frame_8.setGeometry(QtCore.QRect(10, 120, 281, 51))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_58 = QtGui.QLabel(self.frame_8)
        self.label_58.setGeometry(QtCore.QRect(10, 0, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.LA1_chanmode = QtGui.QComboBox(self.frame_8)
        self.LA1_chanmode.setGeometry(QtCore.QRect(150, 20, 121, 21))
        self.LA1_chanmode.setObjectName(_fromUtf8("LA1_chanmode"))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.frame_8)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.LA1_chan = QtGui.QComboBox(self.frame_8)
        self.LA1_chan.setGeometry(QtCore.QRect(70, 20, 71, 21))
        self.LA1_chan.setObjectName(_fromUtf8("LA1_chan"))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.frame_12)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 94, 31))
        self.pushButton.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.progressBar = QtGui.QProgressBar(self.frame_12)
        self.progressBar.setGeometry(QtCore.QRect(10, 50, 281, 16))
        self.progressBar.setStyleSheet(_fromUtf8("QProgressBar:horizontal {\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"background: white;\n"
"padding: 1px;\n"
"text-align: right;\n"
"margin-right: 5ex;\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5, stop: 0 #467, stop:1 white);\n"
"margin-right: 1px; /* space */\n"
"width: 5px;\n"
"}"))
        self.progressBar.setMaximum(2500)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButton_2 = QtGui.QPushButton(self.frame_12)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 10, 94, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.splitter)
        self.frame_9 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 17))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_9.setBaseSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.message_label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_label.sizePolicy().hasHeightForWidth())
        self.message_label.setSizePolicy(sizePolicy)
        self.message_label.setBaseSize(QtCore.QSize(0, 17))
        self.message_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.horizontalLayout.addWidget(self.message_label)
        self.coord_label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coord_label.sizePolicy().hasHeightForWidth())
        self.coord_label.setSizePolicy(sizePolicy)
        self.coord_label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.coord_label.setFont(font)
        self.coord_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coord_label.setObjectName(_fromUtf8("coord_label"))
        self.horizontalLayout.addWidget(self.coord_label)
        self.freezeButton = QtGui.QCheckBox(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freezeButton.sizePolicy().hasHeightForWidth())
        self.freezeButton.setSizePolicy(sizePolicy)
        self.freezeButton.setMaximumSize(QtCore.QSize(100, 10))
        self.freezeButton.setObjectName(_fromUtf8("freezeButton"))
        self.horizontalLayout.addWidget(self.freezeButton)
        self.verticalLayout.addWidget(self.frame_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))

        self.retranslateUi(MainWindow)
        self.edge2edge.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(1)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_3.setCurrentIndex(1)
        self.comboBox_4.setCurrentIndex(1)
        self.LA1_trigmode.setCurrentIndex(0)
        self.LA1_chanmode.setCurrentIndex(1)
        QtCore.QObject.connect(self.active_channel_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.setActiveDigitalChannels)
        QtCore.QObject.connect(self.comboBox_3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch3)
        QtCore.QObject.connect(self.comboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch2)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch1)
        QtCore.QObject.connect(self.comboBox_4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch4)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.measure_interval)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.capture)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Test and Measurement Suite", None))
        self.frame_12.setProperty("class", _translate("MainWindow", "PeripheralCollection", None))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.edge2chan.setItemText(0, _translate("MainWindow", "ID1", None))
        self.edge2chan.setItemText(1, _translate("MainWindow", "ID2", None))
        self.edge2chan.setItemText(2, _translate("MainWindow", "ID3", None))
        self.edge2chan.setItemText(3, _translate("MainWindow", "ID4", None))
        self.edge2chan.setItemText(4, _translate("MainWindow", "-", None))
        self.edge2chan.setItemText(5, _translate("MainWindow", "CH1", None))
        self.edge2chan.setItemText(6, _translate("MainWindow", "Fin", None))
        self.edge1edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge1edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge1edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_16.setText(_translate("MainWindow", "EDGE 1", None))
        self.edge2edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge2edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge2edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_17.setText(_translate("MainWindow", "EDGE 2", None))
        self.edge1chan.setItemText(0, _translate("MainWindow", "ID1", None))
        self.edge1chan.setItemText(1, _translate("MainWindow", "ID2", None))
        self.edge1chan.setItemText(2, _translate("MainWindow", "ID3", None))
        self.edge1chan.setItemText(3, _translate("MainWindow", "ID4", None))
        self.edge1chan.setItemText(4, _translate("MainWindow", "-", None))
        self.edge1chan.setItemText(5, _translate("MainWindow", "CH1", None))
        self.edge1chan.setItemText(6, _translate("MainWindow", "Fin", None))
        self.label_56.setText(_translate("MainWindow", "MEASURE TIME INTERVALS", None))
        self.pushButton_6.setText(_translate("MainWindow", "Go", None))
        self.time_interval_label.setText(_translate("MainWindow", "result:", None))
        self.label_13.setText(_translate("MainWindow", "Channels", None))
        self.frame_5.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.label_54.setText(_translate("MainWindow", "MULTI CHANNEL", None))
        self.label_4.setText(_translate("MainWindow", "CH1 :", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_9.setText(_translate("MainWindow", "CH2 :", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_11.setText(_translate("MainWindow", "CH3 :", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_12.setText(_translate("MainWindow", "CH4 :", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.frame_10.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.label_29.setText(_translate("MainWindow", "trigger", None))
        self.LA1_trig.setItemText(0, _translate("MainWindow", "ID1", None))
        self.LA1_trig.setItemText(1, _translate("MainWindow", "ID2", None))
        self.LA1_trig.setItemText(2, _translate("MainWindow", "ID3", None))
        self.LA1_trig.setItemText(3, _translate("MainWindow", "ID4", None))
        self.LA1_trig.setItemText(4, _translate("MainWindow", "-", None))
        self.LA1_trig.setItemText(5, _translate("MainWindow", "CH1", None))
        self.LA1_trig.setItemText(6, _translate("MainWindow", "Fin", None))
        self.LA1_trigmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.LA1_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.LA1_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.LA1_trigmode.setItemText(3, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.active_channel_box.setItemText(0, _translate("MainWindow", "1", None))
        self.active_channel_box.setItemText(1, _translate("MainWindow", "2", None))
        self.active_channel_box.setItemText(2, _translate("MainWindow", "3", None))
        self.active_channel_box.setItemText(3, _translate("MainWindow", "4", None))
        self.frame_8.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.label_58.setText(_translate("MainWindow", "SINGLE CHANNEL OPTIONS", None))
        self.LA1_chanmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.LA1_chanmode.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.LA1_chanmode.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.LA1_chanmode.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.LA1_chanmode.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_28.setText(_translate("MainWindow", "Channel", None))
        self.LA1_chan.setItemText(0, _translate("MainWindow", "ID1", None))
        self.LA1_chan.setItemText(1, _translate("MainWindow", "ID2", None))
        self.LA1_chan.setItemText(2, _translate("MainWindow", "ID3", None))
        self.LA1_chan.setItemText(3, _translate("MainWindow", "ID4", None))
        self.LA1_chan.setItemText(4, _translate("MainWindow", "-", None))
        self.LA1_chan.setItemText(5, _translate("MainWindow", "CH1", None))
        self.LA1_chan.setItemText(6, _translate("MainWindow", "Fin", None))
        self.pushButton.setText(_translate("MainWindow", "Start", None))
        self.progressBar.setFormat(_translate("MainWindow", "%v", None))
        self.pushButton_2.setText(_translate("MainWindow", "Show", None))
        self.message_label.setText(_translate("MainWindow", "Msg:", None))
        self.coord_label.setText(_translate("MainWindow", "TextLabel", None))
        self.freezeButton.setText(_translate("MainWindow", "FREEZE", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))

